apiVersion: apps/v1
kind: Deployment
metadata:
  name: osrs-track-search
  labels:
    app: osrs-track-search
spec:
  replicas: 2
  selector:
    matchLabels:
      app: osrs-track-search
  template:
    metadata:
      labels:
        app: osrs-track-search
    spec:
      containers:
        - name: osrs-track-search
          image: us-east1-docker.pkg.dev/osrs-track-412507/osrs-track-search/osrs-track-search:latest
          ports:
            - containerPort: 8080
          env:
            - name: NATS_URL
              value: "nats://my-nats.nats.svc.cluster.local:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: osrs-track-search
spec:
  selector:
    app: osrs-track-search
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer