apiVersion: apps/v1
kind: Deployment
metadata:
  name: myApp-deployment
  labels:
    app: osrs-track-search
spec:
  replicas: 2
  selector:
    matchLabels:
      app: osrs-track-search
  template:
    metadata:
      labels:
        app: osrs-track-search
    spec:
      containers:
        - name: osrs-track-search
          image:
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: osrs-track-search
spec:
  selector:
    app: osrs-track-search
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer