name: 'Terraform GitHub Actions'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: 'Setup Google Credentials'
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > account.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${PWD}/account.json" >> $GITHUB_ENV
        working-directory: ./terraform

      - name: 'Terraform Init'
        run: terraform init
        working-directory: ./terraform

      - name: 'Terraform Validate'
        run: terraform validate
        working-directory: ./terraform

      - name: 'Terraform Plan'
        run: terraform plan
        working-directory: ./terraform
        if: github.event_name == 'pull_request'

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve
        working-directory: ./terraform
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
